"""Add enhanced video processing fields

Revision ID: e7ba2f358f6d
Revises: 7b390d6086fb
Create Date: 2025-01-31 01:10:45.259749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7ba2f358f6d'
down_revision: Union[str, None] = '7b390d6086fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
